version: '3.8'
services:
  app:
    build: 
      context: ./
      target: dev
    container_name: 6ixApp
    volumes:
      - .:/app
    command: npm run dev
    environment:
      NODE_ENV: development
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - '80:80'
    # volumes:
    #   - ./data:/data
    #   - ./letsencrypt:/etc/letsencrypt
