version: '3.8'
services:
  app:
    build: 
      context: ./
      target: runner
    container_name: 6ixApp
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
    # These ports are in format <host-port>:<container-port>
      - '80:3000' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt